<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .subtitle {
            font-size: 18px;
            color: #666;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 15px;
            color: #2c3e50;
        }
        .content {
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 14px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $report->title }}</div>
        <div class="subtitle">Generated on {{ now()->format('F j, Y') }}</div>
    </div>

    <div class="section">
        <div class="section-title">Executive Summary</div>
        <div class="content">
            {{ $report->executive_summary }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Project Overview</div>
        <div class="content">
            <table>
                <tr>
                    <th>Project Name</th>
                    <td>{{ $report->project_name }}</td>
                </tr>
                <tr>
                    <th>Client Name</th>
                    <td>{{ $report->client_name }}</td>
                </tr>
                <tr>
                    <th>Start Date</th>
                    <td>{{ $report->start_date }}</td>
                </tr>
                <tr>
                    <th>End Date</th>
                    <td>{{ $report->end_date }}</td>
                </tr>
                <tr>
                    <th>Project Manager</th>
                    <td>{{ $report->project_manager }}</td>
                </tr>
            </table>
        </div>
    </div>

    @if($report->project_objectives)
    <div class="section">
        <div class="section-title">Project Objectives</div>
        <div class="content">
            {{ $report->project_objectives }}
        </div>
    </div>
    @endif

    @if($report->methodology)
    <div class="section">
        <div class="section-title">Methodology</div>
        <div class="content">
            {{ $report->methodology }}
        </div>
    </div>
    @endif

    @if($report->findings)
    <div class="section">
        <div class="section-title">Key Findings</div>
        <div class="content">
            {{ $report->findings }}
        </div>
    </div>
    @endif

    @if($report->recommendations)
    <div class="section">
        <div class="section-title">Recommendations</div>
        <div class="content">
            {{ $report->recommendations }}
        </div>
    </div>
    @endif

    @if($report->risk_heat_map)
    <div class="section">
        <div class="section-title">Risk Heat Map</div>
        <div class="content">
            <!-- Risk heat map visualization would go here -->
            Risk assessment and heat map analysis is included in this report.
        </div>
    </div>
    @endif

    @if($report->audit_checklist)
    <div class="section">
        <div class="section-title">Audit Checklist</div>
        <div class="content">
            <!-- Audit checklist details would go here -->
            Detailed audit checklist and compliance information is included.
        </div>
    </div>
    @endif

    <div class="footer">
        <p>Generated by Report Generator</p>
        <p>{{ config('app.name') }} &copy; {{ date('Y') }}</p>
    </div>
</body>
</html>
